import '@/styles/globals.css';
import { plusJakartaSans } from './fonts';

export const metadata = {
  title: 'Kanban Task Management',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
